[package]
name = "tokio-postgres-rustls"
description = "Rustls integration for tokio-postgres"
version = "0.3.1"
authors = ["jbg <jbg@dtmf.io>"]
repository = "https://github.com/jbg/tokio-postgres-rustls"
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
bytes = "0.5.3"
futures = "0.3.1"
ring = "0.16.9"
rustls = "0.16.0"
tokio = "0.2.6"
tokio-postgres = "0.5.1"
tokio-rustls = "0.12.1"
webpki = "0.21.0"

[dev-dependencies]
env_logger = { version = "0.7.1", default-features = false }
tokio = { version = "0.2.6", features = ["macros"] }
